services:
  maia-chess:
    # build: .
    image: ghcr.io/sogliuzzol/ml_dead_chess_champions:main
    container_name: maia_chess_app
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
